name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest  # The environment used to run the pipeline

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build and start the Docker containers using docker-compose
      - name: Build and Push Docker Image
        run: |
          docker-compose -f docker-compose.yml up -d
